### ISSUE TITLE
Can't seem to get mean-correlation argument to work

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/proteomicsTumorDeconv#161]
I added this step into the `simul-data-comparison.cwl` file and it's not running. I think it's not designed  to work with the cell type files?

```
  get-celltype-cordists:
      run: ../figures/plot-figs.cwl
      in:
        metric:
            valueFrom: "mean-correlation"
        metricType:
            valueFrom: "cellType"
        files:
            source: run-all-algs-by-sig/cell-cor-file
      out:
         [table,fig]
```
